CAMERA_DEVICE = "/dev/video0"
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 15
JPEG_QUALITY = 70

BACK_CAMERA_DEVICE = "/dev/video2"
BACK_CAMERA_WIDTH = 960
BACK_CAMERA_HEIGHT = 540
BACK_CAMERA_FPS = 15
BACK_JPEG_QUALITY = 70
